const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医疗人员管理",
                        "menuJump":"列表",
                        "tableName":"yiliao"
                    }
                ],
                "menu":"医疗人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"乡村志愿者管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"乡村志愿者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"文娱活动管理",
                        "menuJump":"列表",
                        "tableName":"huodong"
                    }
                ],
                "menu":"文娱活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "审核"
                        ],
                        "menu":"活动报名管理",
                        "menuJump":"列表",
                        "tableName":"huodongYuyue"
                    }
                ],
                "menu":"活动报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医疗保健管理",
                        "menuJump":"列表",
                        "tableName":"baojian"
                    }
                ],
                "menu":"医疗保健管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"健康档案管理",
                        "menuJump":"列表",
                        "tableName":"jiankang"
                    }
                ],
                "menu":"健康档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"生活照料管理",
                        "menuJump":"列表",
                        "tableName":"shenghuo"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"生活照料订单管理",
                        "menuJump":"列表",
                        "tableName":"shenghuoOrder"
                    }
                ],
                "menu":"生活照料管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地管理",
                        "menuJump":"列表",
                        "tableName":"tudi"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"土地承包管理",
                        "menuJump":"列表",
                        "tableName":"tudiOrder"
                    }
                ],
                "menu":"土地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"医疗保健类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBaojian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"文娱活动类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuodong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"身体情况管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiankang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"生活照料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShenghuo"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"土地类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTudi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
            {
                "backMenu":[
                   {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"文娱活动管理",
                                "menuJump":"列表",
                                "tableName":"huodong"
                            }
                        ],
                        "menu":"文娱活动管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                ],
                                "menu":"活动报名管理",
                                "menuJump":"列表",
                                "tableName":"huodongYuyue"
                            }
                        ],
                        "menu":"活动报名管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"医疗保健管理",
                                "menuJump":"列表",
                                "tableName":"baojian"
                            }
                        ],
                        "menu":"医疗保健管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"健康档案管理",
                                "menuJump":"列表",
                                "tableName":"jiankang"
                            }
                        ],
                        "menu":"健康档案管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"生活照料管理",
                                "menuJump":"列表",
                                "tableName":"shenghuo"
                            }
                            ,
                            {
                                "buttons":[
                                    "订单",
                                    "查看",
                                    "删除"
                                ],
                                "menu":"生活照料订单管理",
                                "menuJump":"列表",
                                "tableName":"shenghuoOrder"
                            }
                        ],
                        "menu":"生活照料管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"土地管理",
                                "menuJump":"列表",
                                "tableName":"tudi"
                            }
                            ,
                            {
                                "buttons":[
                                    "订单",
                                    "查看",
                                    "删除"
                                ],
                                "menu":"土地承包管理",
                                "menuJump":"列表",
                                "tableName":"tudiOrder"
                            }
                        ],
                        "menu":"土地管理"
                    }
                    /*,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据备份",
                                "menuJump":"列表",
                                "tableName":"beifen"
                            },
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据还原",
                                "menuJump":"列表",
                                "tableName":"huanyuan"
                            }
                        ],
                        "menu":"数据库管理"
                    }*/
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"老人",
                "tableName":"laoren"
            },

            {
                "backMenu":[
                  {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"文娱活动管理",
                                "menuJump":"列表",
                                "tableName":"huodong"
                            }
                        ],
                        "menu":"文娱活动管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"活动报名管理",
                                "menuJump":"列表",
                                "tableName":"huodongYuyue"
                            }
                        ],
                        "menu":"活动报名管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                ],
                                "menu":"医疗保健管理",
                                "menuJump":"列表",
                                "tableName":"baojian"
                            }
                        ],
                        "menu":"医疗保健管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                ],
                                "menu":"健康档案管理",
                                "menuJump":"列表",
                                "tableName":"jiankang"
                            }
                        ],
                        "menu":"健康档案管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"生活照料管理",
                                "menuJump":"列表",
                                "tableName":"shenghuo"
                            }
                            ,
                            {
                                "buttons":[
                                    "订单",
                                ],
                                "menu":"生活照料订单管理",
                                "menuJump":"列表",
                                "tableName":"shenghuoOrder"
                            }
                        ],
                        "menu":"生活照料管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"土地管理",
                                "menuJump":"列表",
                                "tableName":"tudi"
                            }
                            ,
                            {
                                "buttons":[
                                    "订单",
                                ],
                                "menu":"土地承包管理",
                                "menuJump":"列表",
                                "tableName":"tudiOrder"
                            }
                        ],
                        "menu":"土地管理"
                    }
                    /*,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据备份",
                                "menuJump":"列表",
                                "tableName":"beifen"
                            },
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据还原",
                                "menuJump":"列表",
                                "tableName":"huanyuan"
                            }
                        ],
                        "menu":"数据库管理"
                    }*/
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"医疗人员",
                "tableName":"yiliao"
            },
]
    }
}
export default menu;
